### ISSUE TITLE
jsonl找不到的错误

### ISSUE THREAD

**Issue by donghaiwang** [shibing624/code-autocomplete#3]
运行training_wizardcoder_mydata.py文件时，load_dataset函数出现错误：
FileNotFoundError: Unable to find 'D:\work\workspace\gpt\webui\data/code_alpaca_20k_50.jsonl' at D:\work\workspace\gpt\webui

请问这个为什么多了一个目录前缀，导致找不到，谢谢

**Comment by shibing624** [comment]
写绝对路径
